### PR TITLE
Added "_.isEqual()" and "_.has()" methods

### PR DESCRIPTION
**Pull request by olivierphi**
Hi !

This is a simple transposition of Underscore.js `isEqual()` and `has()` methods.
I haven't completely tested these 2 new functions, but in my current application use cases (comparisons of 2 Objects and comparisons of 2 Arrays) it seems to work well...

### CODE REVIEW

**Comment by amacdougall** [comment]
Awesome, thanks for the pull request! I'll test it a bit later in the day.

**Comment by amacdougall** [comment]
I wrote some unit tests for `_.isEqual`, and found that it fails in a few cases, such as when comparing two Numbers. Please check out [amacdougall/isEqual_tests](https://github.com/amacdougall/underscore.as/commits/isEqual_tests) and see if you can get them to pass. Once you do, merge them back into your master branch to update this pull request. I really appreciate the work you've done! Looking forward to merging the change.

An implementation suggestion -- if `_.isEqual` should be able to compare scalars such as Numbers or Strings, you can't rely on `Object.toString` to get class names. Instead, use [flash.utils.getQualifiedClassName](http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/utils/package.html#getQualifiedClassName%28%29), which should be much more reliable. This, and the `instanceOf` and `is` operators, should let you simplify the code significantly, taking advantage of ActionScript and avoiding the cruftiness of its JavaScript origin.

**Comment by olivierphi** [comment]
Yeah, I'm sorry ; I just made a straight copy/paste from underscore.js, added some types, and saw it was working for my own precise needs ; not a transposition I could be proud of :-/
I think the `===` operator could be useful too, it's a good ActionScript/Javascript way to know if 2 scalars are strictly equal.
I will make a cleaner Pull Request soon !

**Comment by amacdougall** [comment]
It's okay! I really appreciate the help. That's why we write these kinds of things, right? To solve our own problems!

**Comment by olivierphi** [comment]
Well, I fixed `_.isEqual()` (its Flex Unit is correct now).
I also added `_.difference()` (I just copied your `_.intersect()` function and inverted the nested condition). Not "FlexUnit-tested", but it works well in my application with two Arrays of integers.

By the way, is there a particular reason to the original Underscore `_.intersection()` function name switched to `_.intersect()` in your ActionScript version ? :-)

**Comment by olivierphi** [comment]
(Ah, I also added a simple `_.isFunction()`)

**Comment by olivierphi** [comment]
I also tested this `_.isEqual` implementation with Objects like Dates, and it still work. However, it still uses `Object.toString` instead of specific ActionScript tools like `flash.utils.getQualifiedClassName`; although it would probably be better to use these specific ActionScript methods, it still works when comparing 2 empty instances of the same class. 
It doesn't traverses instances properties, however, and don't detect if 2 instances of the same class are "equal" (i.e. their properties values are recursively equal). Maybe we could use serialization for such a test ?

**Comment by olivierphi** [comment]
ByteArray serialization seems to work well in order to compare 2 instances of the same class, all my own tests runs well
:-)

**Comment by amacdougall** [comment]
Added a unit test for `_.difference`; everything passed! I've merged your feature implementations into the trunk. Thanks very much for your work! I hope this helps everyone who uses this library.

**Comment by amacdougall** [comment]
The ByteArray serialization was a good idea, by the way. It might be overkill, but AS3 is fast, and it's probably wise to favor strict equality over maximum speed.

**Comment by amacdougall** [comment]
And a good question about intersect vs intersection... I think I was just asleep at the switch that day. I'll add `intersection` as an alias, to avoid breaking code for anyone who uses `intersect`.

**Comment by amacdougall** [comment]
I didn't know about [Transient], but I can definitely see how that would throw things off. And as in @jiaweihli's Countdown example, information hiding of any kind of makes complex object comparisons very difficult. Personally, I'm in favor of comparing simple collections (such as Arrays and Objects) by their nested elements, while falling back on object identity for complex objects. Where an `isEqual` method exists, use it. Just got back from a vacation, and it's too late for me to do any deep thinking right this moment, but I'll reopen this pull request while we discuss it further.

**Comment by amacdougall** [comment]
I've been thinking about it, and I guess I don't see an easy way to check equality of arbitrary complex objects, especially where private or transient properties are involved. It's good to take advantage of a custom `isEqual` function where it exists; beyond that, I don't think there's anything we can do.

The question I put to you is this: is it better to use @DrBenton 's serialization strategy to at least attempt to check true equality? Or just fall back to standard equality, `==`, and document the behavior clearly? I think @jiaweihli has demonstrated that serialization is not completely reliable, but it might be good enough for a lot of cases... but it also imposes overhead, and it might cause more confusion than it cures.

Suggestions? I'm leaning toward removing the serialization test and just using standard equality. I'm not so concerned about speed, but I'd like to keep the implementation as unsurprising as possible rather than catch all cases. What was possible in JS isn't necessarily possible in AS3, sadly.

**Comment by jklmli** [comment]
I don't think we should use `ByteArray` serialization, but revert to the previous deep comparisons.  This solves the problem of transient properties.

For the problem of private properties on custom class instances, I think notifying the user somehow when they use the `_.isEqual` method on custom class instances without an `isEqual()` method would be ideal...I don't think it's possible to add custom warnings without building out your own linter though.  Maybe just documenting it thoroughly as you mentioned would be okay.

I think deep comparisons (more involved) vs object equality (trivially easy) is a better implementation.

**Comment by olivierphi** [comment]
I personnaly agree for deeps comparisons use, but not about notifying users when they use `_.isEqual` on class instances without `isEqual` methods.
[As I said before](https://github.com/amacdougall/underscore.as/pull/2#commitcomment-1754106), we also have private properties in Javascript, but Underscore.js doesn't try to handle it.
As developer we have to know the possibilities of the languages we use, and should know that deep comparison on objects are limited to public members - this is exactly the reason why we have the `public`, `private`, `internal`... namespaces. Thus, when using `_.isEqual` on 2 complex objects like class instances we should know that this comparison will be based - by the language design - on "public" properties.
My 2 cents... :-)

**Comment by amacdougall** [comment]
So, do you gentlemen think it would be enough to compare explicitly
enumerable properties head to head and use that as the basis for complex
object equality? We can assert, at least, that the observable properties of
two objects are the same. It doesn't seem like it's possible to behave
exactly the same as underscore.js here.

**Comment by olivierphi** [comment]
Well, this would be fine for me. For more complex objects, developers can still implement `isEqual` methods on their classes if they want to use `_.isEqual()` with them.

**Pull request merged**
